[package]
name = "celeste_cli"
version = "0.1.0"
edition = "2024"

publish = false

[package.metadata.dist]
dist = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
celeste_rs = { path = "../lib" }
